# core

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/billing_core
    username: billing
    password: abc123

logging:
  level:
    tech.jannotti.billing.core: INFO
    org.hibernate.SQL: INFO
    org.springframework.ws.client.MessageTracing.sent: INFO
    org.springframework.ws.client.MessageTracing.received: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%-5level] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%-5level] %logger{36} - %msg%n"

liquibase:
  enabled: true
  change-log: classpath:liquibase/changelog.xml
  contexts: dev

core:
  invoice:
    alerting:
      daysBeforeExpirationToAlert: 5
  subscription:
    invoice:
      daysBeforeExpirationToCreate: 10
  httpClient:
    pooling:
      max:
        total: 100
        perRoute: 10
      request:
        timeout: 1000
    socket:
      buffer:
        size: 1024
    keyStore:
      path: /httpClient/keystore.p12
      type: PKCS12
      password: "36W%Ml6aNv#f"
  email:
    connector: emailConnectors.sendGrid
    from: noreply@jannotti.tech
    sendGrid:
      url: https://api.sendgrid.com/v3/mail/send
      apiKey: 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
  notification:
    deliveryDelay: 3000 # 3 segundos
    requestTimeout: 30000 # 30 segundos
    retryLimit: 3
    retryDelay: 3600000 # 1 hora

# batch

server:
  port: 9090

batch:
  jobs:
    invoice:
      invoicesExpiration:
        cron: 0 0 0 * * ? # meia noite
      invoicesAlerting:
        cron: 0 0 9 * * ? # 9h da manha
    subscription:
      finishedSubscriptions:
        cron: 0 10 0 * * ? # meia noite e dez
      subscriptionInvoices:
        cron: 0 15 0 * * ? # meia noite e quinze
    market:
      marketBalancesSummary:
        cron: 0 30 0 * * ? # meia noite e meia
    banking:
      bb:
        bankRemittances:
          cron: 0 */10 * * * ? # de 10 em 10 minutos, no segundo 0
        bankDischarges:
          cron: 30 */10 * * * ? # de 10 em 10 mintuos, no segundo 30
        unpaidBankBillets:
          cron: 0 30 0 * * ? # meia noite e meia
      santander:
        bankRemittances:
          cron: 15 */10 * * * ? # de 10 em 10 minutos, no segundo 15
        bankDischarges:
          cron: 45 */10 * * * ? # de 10 em 10 mintuos, no segundo 45
        unpaidBankBillets:
          cron: 0 45 0 * * ? # meia noite e quarenta e cinco

sentry:
  enabled: false  
  dsn: https://e69a994da8e14aad90426710fa0825ae@sentry.io/1245521
  environment: local
